import WeekForm from "@/components/WeekForm";
import Navbar from "@/components/layouts/Navbar";
import Head from "next/head";
import React from "react";

const create = () => {
  return (
    <>
      <Head>
        <title>تحصين الٍران | بالحصون الخمسة</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen w-full flex-col items-end justify-start font-elmessiri" dir="rtl"
      >
        <Navbar />

        <div className="mx-auto w-full bg-base-200">
          <div dir="rtl" className="container mx-auto min-h-screen w-full">
            <h2 className="my-12 mt-8 text-5xl">بيانات الاسبوع</h2>
            <WeekForm />
          </div>
        </div>

        {/* Footer */}
        <footer className="footer mx-auto items-center justify-center bg-neutral p-4 text-neutral-content">
          <div className="items-center">
            <p>
              حقوق النشر محفوظة © 2022 تم تطويره بواسطة
              <a
                target="_blank"
                className="mx-1 text-warning"
                href="https://www.linkedin.com/in/abdelrahman114/"
              >
                عبدالرحمن أحمد عباس
              </a>
            </p>
          </div>
        </footer>
      </main>
    </>
  );
};

export default create;
